select 
--*
X.VOUCHER_NO, X.ACCOUNTING_YEAR,X.VOUCHER_DATE,X.ROW_NO,X.ACCOUNT,X.ACCOUNT_DESC,X.CODE_B,X.CODE_B_DESC,
X.CODE_C,X.CODE_C_DESC,X.CODE_H,X.DEBET_AMOUNT,X.CREDIT_AMOUNT,X.AMOUNT,X.QUANTITY,X.REFERENCE_SERIE,X.REFERENCE_NUMBER,
X.MPCCOM_ACCOUNTING_ID,X.OBJVERSION,
y.TRANS_REVAL_EVENT_ID

from GEN_LED_VOUCHER_ROW_UNION_QRY x , MPCCOM_ACCOUNTING y
where 
x.VOUCHER_TYPE = 'MPL' and x.VOUCHER_NO = 2022020339 and x.ACCOUNTING_YEAR = 2022 and 
x.ROW_NO in (
'3864',
'3846',
'3898',
'3882',
'3830'
)
and X.MPCCOM_ACCOUNTING_ID=Y.ACCOUNTING_ID
and X.DEBET_AMOUNT=Y.DEBIT_AMOUNT
