SELECT INVOICE_PARTY_TYPE_GROUP_API.Get_Description(j.COMPANY, j.PARTY_TYPE, j.GROUP_ID) Region, 
i.IDENTITY, i.IDENTITY_NAME, CONCAT(i.LEDGER_ITEM_SERIES_ID,i.LEDGER_ITEM_ID) invoice_no, 
TO_CHAR(i.LEDGER_DATE,'MM/DD/YYYY') INVOICE_DATE, i.INV_AMOUNT, i.OPEN_AMOUNT, ROUND(SYSDATE-i.LEDGER_DATE) ""Days count @ Today""

FROM LEDGER_ITEM_CU_DET_QRY i, IDENTITY_PAY_INFO_CU_QRY j

WHERE i.IDENTITY=j.IDENTITY AND i.IDENTITY like 'LOC%' AND j.GROUP_ID NOT LIKE 'RICE' AND i.FULLY_PAID = 'FALSE'
        AND i.LEDGER_DATE between to_date(20110101,'YYYYMMDD' ) and to_date(SYSDATE)
        
ORDER BY 2